version: "3.8"
volumes:
  db-store:
  php-fpm-socket:
services:
  app:
    build: ./php
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/work/www/html

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ../:/work/www/html

  mysql:
    build: ./mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=app_user
      - PMA_PORT=3307
      - PMA_PASSWORD=app_secret
    ports:
      - "6002:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions